version: "3.5"

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: "node_exporter"
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
      - /:/host:ro
    command:
      - --path.rootfs=/host
      - --web.listen-address=:9100
    networks:
      - default
networks:
  mynetwork:
    driver: bridge
